### ISSUE TITLE
update ccli, add different alies

### ISSUE THREAD

**Issue by batasu** [farhansadik/echominal-development#11]
need to remove CCLi and add simple alias instead of ccli

**Comment by farhansadik** [comment]
New ccli commands has been added for test. By @batasu 

Waiting for test result from @squaredevops

**Comment by batasu** [comment]
cat: .config/ccli/termux.cfg: No such file or directory
/data/data/com.termux/files/home/.oh-my-zsh/tools/check_for_upgrade.sh:
line 32: syntax error near unexpected token `)'
/data/data/com.termux/files/home/.oh-my-zsh/tools/check_for_upgrade.sh:
line 32: `() {'
/data/data/com.termux/files/home/.oh-my-zsh/oh-my-zsh.sh: line 21:
autoload: command not found
/data/data/com.termux/files/home/.oh-my-zsh/oh-my-zsh.sh: line 39: syntax
error near unexpected token `('
/data/data/com.termux/files/home/.oh-my-zsh/oh-my-zsh.sh: line 39: `for
plugin ($plugins); do'
/data/data/com.termux/files/home/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh:
line 31: alias: -L: invalid option
alias: usage: alias [-p] [name[=value] ... ]
/data/data/com.termux/files/home/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh:
line 36: unalias: -m: invalid option
unalias: usage: unalias [-a] name [name ...]
/data/data/com.termux/files/home/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh:
line 39: 0=${(%):-%N}: bad substitution
/data/data/com.termux/files/home/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh:
line 42: /.version: No such file or directory
/data/data/com.termux/files/home/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh:
line 43: /.revision-hash: No such file or directory
/data/data/com.termux/files/home/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh:
line 104: autoload: command not found
/data/data/com.termux/files/home/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh:
line 105: is-at-least: command not found
/data/data/com.termux/files/home/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh:
line 188: syntax error near unexpected token `}'
/data/data/com.termux/files/home/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh:
line 188: `  if [[ $WIDGET == zle-isearch-update ]] && {
$zsh_highlight__pat_static_bug || ! (( $+ISEARCHMATCH_ACTIVE )) }; then'
cat: .config/ccli/termux.cfg: No such file or directory

**Comment by farhansadik** [comment]
CCLI error has been fixed for now
