### ISSUE TITLE
Fix repository issue 

### ISSUE THREAD

**Issue by farhansadik** [farhansadik/echominal-development#18]
Need to fix repository issue ASAP 
find a way to fix `sources.list` 

Farhan Sadik

**Comment by batasu** [comment]
try to reset all environment and settings in android real time device 
need to work with `change-termux-repo`

**batasu**

**Comment by farhansadik** [comment]
This is perfectly fine in `termux 0.113` from https://f-droid.org/en/packages/com.termux/

This https://wiki.termux.com/wiki/FAQ web site says, 

> Minimal Android version ever supported is **5.0**, but its support is already dropped since **2020.01.01** to reduce load on maintainers as older Android versions have more problems.
Android 4.4.x (KitKat) was never supported at all. You may take this challenge of porting packages yourself, though it is strongly recommended (not just in Termux scope) to have up-to-date Android OS.
Packages compiled for **Android 7** may not run on older versions like **5.x** and **6.x**.

**Farhan Sadik**
I don't have suitable android device to run termux right now. sorry... for that. But @squaredevops will keep testing for us.
