### ISSUE TITLE
Backup and Restore Error 

### ISSUE THREAD

**Issue by squaredevops** [farhansadik/echominal-development#22]
```
[*] archiving has been finished
[*] creating backup directory
[*] created
[*] preparing for copy files to /sdcard
mv: preserving times for '/sdcard/termux-backup/2021-06-10_20:52.zip': Operation not permitted
mv: preserving permissions for ‘/sdcard/termux-backup/2021-06-10_20:52.zip’: Operation not permitted
[*] backup process has been finished
```

But `/sdcard/termux-backup/2021-06-10_20:52.zip` file is being found in storage location.
File Size **704MB**

**Android Tester**

**Comment by farhansadik** [comment]
**Possible Solution**
Copy **zip** file to the **storage** location and then delete that file. This could be a possible solution. @batasu please take a look at this. I don't have suitable android device can't test.

**Farhan Sadik**

**Comment by squaredevops** [comment]
I've a temporary solution and it worked! for me! 

output :
```
[*] archiving has been finished
[*] creating backup directory
[*] created
[*] preparing for copy files to /sdcard
[*] backup process has been finished
[*] pre file has been deleted
```

**Comment by farhansadik** [comment]
@squaredevops great work but you've remove `usr` from backing up. I'm adding up again and let me know the result. 

**Farhan Sadik**

**Comment by squaredevops** [comment]
Everything seemed fine. Here is the output : 
```
[*] archiving has been finished
[*] creating backup directory
[*] backup directory created
[*] preparing for copy files to /sdcard
[*] backup process has been finished
[*] copying backup file to /sdcard
[*] file copied
```
1. Spelling Mistake `copied  copying`
2. While `preparing for copy files to /sdcard` it tool a while to complete this process. you can add a loading animation or a **please wait** text.

**Comment by farhansadik** [comment]
Thanks for the typing mistake. And I've also added **please wait** text.
