### ISSUE TITLE
task.txt

### ISSUE THREAD

**Issue by farhansadik** [farhansadik/echominal-development#29]
`task.txt` file has been empty how this was happened? find out old files, we need it!

**Comment by batasu** [comment]
**Found lost treasure** 
* Oneline commit 
```
da09697 auto commit - updated
```
* Log 
```
commit da096975f17e5bdb2025fb623f2dab9be888ad19
Author: Farhan Sadik <farhansadikriduan@gmail.com>
Date:   Fri Jun 11 04:12:09 2021 +0600

    auto commit - updated

```
Looks like this mistake was done by @farhansadik 

* Lost Treasure 
[tasks.txt](https://github.com/farhansadik/echominal-development/files/6644399/tasks.txt)
