### ISSUE TITLE
Tools & Utilities

### ISSUE THREAD

**Issue by batasu** [farhansadik/echominal-development#34]
## Tools & Utilities 
> Main Menu > 2 > 4 5 6 7 

**Nominated Options  :**
* termux-media-player
* termux-notification
* termux-notification-remove       
* termux-open-url         
* termux-reset           
* termux-wake-lock
* termux-fix-shebang      
* termux-open             
* termux-reload-settings  
* termux-setup-storage    
* termux-wake-unlock

This API has lots of tools :
https://wiki.termux.com/wiki/Termux:API

**Primary Selection :** 
1. hget - https://github.com/bevacqua/hget (converts html site to a plain text) it can be add into utilities/tools or network tools
2. Networking Tools (netstat ifconfig ip link)
3. termux-media-player
4. Node.js [done]

**Slot** 
1. Htop [Monitoring Tools]
2. Python 3 
3. Node.js
4. Termux API
8. Convert MP3 from Youtube 
9. File Manager [CLI]

**Comment by squaredevops** [comment]
## Termux API
### Wifi Enable/Disable
```bash
termux-wifi-enable false
termux-wifi-enable true
```
### termux-wifi-scaninfo
```bash 
[
  {
    "bssid": "62:e2:66:d7:38:44",
    "frequency_mhz": 5240,
    "rssi": -50,
    "ssid": "VirtWifi",
    "timestamp": 249000511760,
    "channel_bandwidth_mhz": "20"
  }
]
```
### termux-wifi-connectioninfo
```bash
{
  "bssid": "62:e2:66:d7:38:44",
  "frequency_mhz": 5240,
  "ip": "10.0.2.15",
  "link_speed_mbps": 1,
  "mac_address": "02:00:00:00:00:00",
  "network_id": 0,
  "rssi": -50,
  "ssid": "VirtWifi",
  "ssid_hidden": false,
  "supplicant_state": "COMPLETED"
}
```
### termux-battery-status
```bash 
{
  "health": "UNKNOWN",
  "percentage": 0,
  "plugged": "PLUGGED_AC",
  "status": "UNKNOWN",
  "temperature": 0.0,
  "current": -9223372036854775808
}
```
### termux-sensor -l
```bash
{
  "sensors": [
    "Kbd Orientation Sensor"
  ]
}
```
### `termux-telephony-call 999`
### `termux-sms-send -n 998 "this is a message"`
### termux-telephony-deviceinfo
```bash
{
  "data_activity": "none",
  "data_state": "disconnected",
  "device_id": null,
  "device_software_version": null,
  "phone_count": 1,
  "phone_type": "gsm",
  "network_operator": "",
  "network_operator_name": "",
  "network_country_iso": "",
  "network_type": "unknown",
  "network_roaming": false,
  "sim_country_iso": "",
  "sim_operator": "",
  "sim_operator_name": "",
  "sim_serial_number": null,
  "sim_subscriber_id": null,
  "sim_state": "unknown"
}
```
### termux-wallpaper
```bash
termux-wallpaper -f images/development.png
Wallpaper set successfully!
```

**Comment by squaredevops** [comment]
### termux-media-player
```bash 
Usage: termux-media-player cmd [args]

help        Shows this help
info        Displays current playback information
play        Resumes playback if paused
play <file> Plays specified media file
pause       Pauses playback
stop        Quits playback
```
### termux-notification
Media actions (available with --type "media"):
```bash
 --media-next             action to execute on the media-next button
 --media-pause            action to execute on the media-pause button
 --media-play             action to execute on the media-play button
 --media-previous         action to execute on the media-previous button
```
### termux-notification-remove

https://wiki.termux.com/wiki/Termux-notification
