### ISSUE TITLE
System Maintenance

### ISSUE THREAD

**Issue by batasu** [farhansadik/echominal-development#35]
## System Maintenance

> Main Menu > 3 > 7 8

**Nominated Options :** 
* Termux GUI (https://wiki.termux.com/wiki/Graphical_Environment)
* hget - https://github.com/bevacqua/hget (converts html site to a plain text) **[MOVED TO TOOLS AND UTILITIES]**
* Netstat

**Primary Selection :** 
1. Termux GUI [on test]

**Comment by farhansadik** [comment]
Approved! @batasu
1. move **hget** to `tools and utilities`
2. https://github.com/adi1090x/termux-desktop

**Comment by batasu** [comment]
## Notice 
We better update/implement it letter. Now focus to other option's like `Tools and Utilities`. Because it has already 5 slot empty.
