### ISSUE TITLE
Reboot to Recovery Mode

### ISSUE THREAD

**Issue by farhansadik** [farhansadik/echominal-development#41]
## Reboot to Recovery Mode
`main > 3 > 10`

1. Method 1 
```bash 
# su -c reboot recovery 
```
2. Method 2 
Generally, `reboot` binary provides a `recovery` switch. After switching to root, execute this command:
```bash 
/system/bin/reboot recovery
```
https://android.stackexchange.com/questions/21050/enter-recovery-mode-from-command-line
https://www.trishtech.com/2015/03/reboot-android-into-recovery/

**Comment by squaredevops** [comment]
Method 1 worked without `-c`. Command was 
> termux-sudo or root access required!

```bash 
$ sudo reboot recovery
```
Method 2 is worked in my device !

**Comment by squaredevops** [comment]
### v0.1.22 patch 
Patch worked! but stucked in `grub` while booting. I'll have to **reboot** again for boot.

**Comment by farhansadik** [comment]
It's because of you don't have recovery system. You're using `android x86` in virtual box!
